---
title: "DSE 511 Question List"
format: html
editor: visual
---

## System Setup

```{r, warning = FALSE, message = FALSE}
library(readr)
library(arrow)
library(dplyr)
library(ggplot2)

# load data
complaint_data <- read_parquet("../../raw_data/complaint_data_2019_2024.parquet.gz")
tr_results <- read_parquet("../../data_embeddings/topic_results.parquet")
```

## Q1 - Are more complaints happening over time?

Answer: They are actually decreasing as time goes on; whether that's because the new cars have just been on the road less is something to be answered.

```{r}
# aggregate
year_complaint_count <- complaint_data |> 
  group_by(model_year) |> 
  count()

# plot
ggplot(year_complaint_count, aes(x = model_year, y = n)) +
  geom_col(fill = "blue") +
  scale_x_continuous(
    breaks = seq(min(year_complaint_count$model_year),
                 max(year_complaint_count$model_year),
                 by = 1)
  ) +
  labs(
    title = "Complaints by Model Year",
    x = "Model Year",
    y = "Number of Complaints"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold", size = 16, hjust = 0.5),
    axis.title.x = element_text(margin = margin(t = 10)),
    axis.title.y = element_text(margin = margin(r = 10))
  )
```

------------------------------------------------------------------------

## Q2 - Which parent companies receive the most complaints?

Answer:

```{r}


```

### Q2.1 - How do the complaints for parent companies trend over time?

Answer:

```{r}

```

## Q3 - Which models receive the most complaints?

Answer:

```{r}

```


### Q3.1 - For the worst models, how do their complaints trend over time?

Answer:

```{r}

```

## Q4 - What are the most common topics?

Answer:

```{r}
tr_label_count <- tr_results |> 
  filter(
    topic != -1
  ) |> 
  group_by(topic, topic_label) |> 
  count()


ggplot(head(tr_label_count, 10), aes(x = reorder(topic_label, -n), y = n)) +
  geom_col() +
  labs(
    x = NULL,
    y = NULL
  ) +
  theme(
    axis.text.x = element_text(angle = 60, hjust = 1)
  )
```

## Q4.1 - How do the top topics trend over time?

```{r}
tr_label_count <- tr_results |> 
  filter(
    topic != -1
  ) |> 
  group_by(topic, topic_label) |> 
  count()

tr_year_label_count <- tr_results |> 
  filter(
    topic %in% head(tr_label_count$topic, 12) &
    topic != -1
  ) |> 
  group_by(topic, topic_label, model_year) |> 
  count() |> 
  arrange(
    desc(n)
  )

ggplot(tr_year_label_count, aes(x = model_year, y = n, fill = topic_label)) +
  geom_col() +
  facet_wrap(~ topic_label) + 
  labs(
    x = NULL,
    y = NULL
  ) +
  theme(
    axis.text.x = element_text(angle = 60, hjust = 1)
  )
```

### Q4.2 - What are the most common topics given a component?

Answer:

```{r}
tr_count <- tr_results |> 
  filter(
    topic != -1
  ) |> 
  group_by(topic, topic_label, components) |> 
  count() |> 
  arrange(
    desc(n)
  )


ggplot(head(tr_count, 10), aes(x = reorder(topic_label, -n), y = n, fill = components)) +
  geom_col() +
  labs(
    x = NULL,
    y = NULL
  ) +
  theme(
    axis.text.x = element_text(angle = 60, hjust = 1)
  )
```
# How do these trend over time?

```{r}
tr_year_count <- tr_results |> 
  filter(
    topic %in% head(tr_count$topic, 10) &
    topic != -1
  ) |> 
  group_by(topic, topic_label, components, model_year) |> 
  count() |> 
  arrange(
    desc(n)
  )


ggplot(tr_year_count, aes(x = model_year, y = n, fill = topic_label)) +
  geom_col() +
  facet_wrap(~ components) + 
  labs(
    x = NULL,
    y = NULL
  ) +
  theme(
    axis.text.x = element_text(angle = 60, hjust = 1)
  )
```

------------------------------------------------------------------------

## Q5 - Are new cars getting worse?

Answer: Not necessarily, or at least from the complaints data, it seems like they are getting better...

```{r}

```